#!/bin/bash
#
# cvs up + vimdiff + shortcuts
# mahaek
#
# usage: vd FILENAME
#

vdVERBOSE=true
vdUSERSUFFIX=`id -nu`
vdLOCALSUFFIX=$vdUSERSUFFIX"LOCAL"
vdEDITSUFFIX=$vdUSERSUFFIX"EDIT"

vdORIGINAL=${@:${#@}}
vdUPDATEOPTS=${@:1:$((${#@} - 1))}

function vprint {
  if [ $vdVERBOSE ]
  then
    echo $*
  fi
}

function vLocalVimdiff {
  # set filetype to extension before vdLOCALSUFFIX
  vimdiff --cmd \
      'autocmd BufRead *.*.'${vdLOCALSUFFIX}' exec "doau filetypedetect BufRead ".expand("%:t:r")' \
      $vdORIGINAL $vdORIGINAL.${vdLOCALSUFFIX}
}

function vCommit {
  echo -ne "commit message: "
  read msg
  echo "committing $vdORIGINAL..."
  cvs commit -m "$msg" $vdORIGINAL
}

function vCommitTag {
  vCommit
  if [ $# -lt 1 ]
  then
    echo -ne "tag: "
    read tag
  else
    tag=$1
  fi
  echo "tagging $vdORIGINAL $tag..."
  cvs tag -F $tag $vdORIGINAL
}

# check file exists
if [ $# -lt 1 ]
then
  echo "usage: vd [CVS_UP_OPTIONS] FILENAME"
  exit
elif [ ! -n $vdORIGINAL ]
then
  echo "usage: vd [CVS_UP_OPTIONS] FILENAME"
  exit
elif [ -d $vdORIGINAL ]
then
  echo "$vdORIGINAL is a directory"
  exit
elif [ ! -e $vdORIGINAL ] 
then 
  echo $vdORIGINAL": file not found"
  exit
fi

vprint -e "cp $vdORIGINAL $vdORIGINAL.${vdLOCALSUFFIX}"
cp $vdORIGINAL $vdORIGINAL.${vdLOCALSUFFIX}
vprint -e "rm $vdORIGINAL; cvs up $vdUPDATEOPTS $vdORIGINAL"
rm $vdORIGINAL; cvs up $vdUPDATEOPTS $vdORIGINAL

# check file exists
if [ ! -e $vdORIGINAL ] 
then 
  echo $vdORIGINAL": file not found in cvs, undoing (check cvs errors)"
  vprint "cp $vdORIGINAL.${vdLOCALSUFFIX} $vdORIGINAL"
  cp $vdORIGINAL.${vdLOCALSUFFIX} $vdORIGINAL
  exit
fi

vLocalVimdiff

vprint -e "\nHISTORY"
vprint -e "\tcp $vdORIGINAL $vdORIGINAL.${vdLOCALSUFFIX}"
vprint -e "\trm $vdORIGINAL; cvs up $vdORIGINAL"
vprint -e "\tvimdiff $vdORIGINAL $vdORIGINAL.$vdLOCALSUFFIX"

while true; do
  echo -e "\nCOMMANDS "
  echo -e "\tl\tshow current files"
  echo -e "\td\tshow cvs diff"
  echo -e "\tv\tback to vimdiff"
  echo -e "\tc\tcvs commit, restore local copy, and exit (keep backups)"
  echo -e "\tC\tcvs commit, restore local copy, and exit (delete backups)"
  echo -e "\tct\tcvs commit, tag, restore local copy, and exit (keep backups)"
  echo -e "\tCt\tcvs commit, tag, restore local copy, and exit (delete backups)"
  echo -e "\tcc\tcvs commit, tag CUR, restore local copy, and exit (keep backups)"
  echo -e "\tCc\tcvs commit, tag CUR, restore local copy, and exit (delete backups)"
  echo -e "\tu\tbackup edited file, undo, and exit (keep backups)" 
  vprint -e "\t\t\tcp $vdORIGINAL $vdORIGINAL.${vdEDITSUFFIX}"
  vprint -e "\t\t\tcp $vdORIGINAL.${vdLOCALSUFFIX} $vdORIGINAL"
  echo -e "\tU\tdiscard edited file, undo, and exit (delete backups)" 
  vprint -e "\t\t\tmv $vdORIGINAL.${vdLOCALSUFFIX} $vdORIGINAL"
  echo -e "\tx\texit"
  echo -ne "\nenter cmd: "
  read cmd
  case $cmd in
    u)
      vprint "undoing"
      vprint "cp $vdORIGINAL $vdORIGINAL.${vdEDITSUFFIX}"
      cp $vdORIGINAL $vdORIGINAL.${vdEDITSUFFIX}
      vprint "cp $vdORIGINAL.${vdLOCALSUFFIX} $vdORIGINAL"
      cp $vdORIGINAL.${vdLOCALSUFFIX} $vdORIGINAL
      break
      ;;
    U)
      vprint "undoing (delete backups)"
      vprint "mv $vdORIGINAL.${vdLOCALSUFFIX} $vdORIGINAL"
      mv $vdORIGINAL.${vdLOCALSUFFIX} $vdORIGINAL
      break
      ;;
    l)
      echo -e "\nCURRENT FILES"
      ls -lt $vdORIGINAL*
      ;;
    d)
      echo "getting cvs diff..."
      cvs diff $vdORIGINAL
      echo "end of cvs diff"
      ;;
    v)
      vLocalVimdiff
      ;;
    c)
      #echo -ne "commit message: "
      #read msg
      #echo "committing $vdORIGINAL..."
      #cvs commit -m "$msg" $vdORIGINAL
      vCommit
      vprint "cp $vdORIGINAL.$vdLOCALSUFFIX $vdORIGINAL"
      cp $vdORIGINAL.$vdLOCALSUFFIX $vdORIGINAL
      exit
      ;;
    C)
      #echo -ne "commit message: "
      #read msg
      #echo "committing $vdORIGINAL..."
      #cvs commit -m "$msg" $vdORIGINAL
      vCommit
      vprint "mv $vdORIGINAL.$vdLOCALSUFFIX $vdORIGINAL"
      mv $vdORIGINAL.$vdLOCALSUFFIX $vdORIGINAL
      exit
      ;;
    ct)
      #echo -ne "commit message: "
      #read msg
      #echo -ne "tag: "
      #read tag
      #echo "committing $vdORIGINAL..."
      #cvs commit -m "$msg" $vdORIGINAL
      #echo "tagging $vdORIGINAL $tag..."
      #cvs tag -F $tag $vdORIGINAL
      vCommitTag
      vprint "cp $vdORIGINAL.$vdLOCALSUFFIX $vdORIGINAL"
      cp $vdORIGINAL.$vdLOCALSUFFIX $vdORIGINAL
      exit
      ;;
    Ct)
      #echo -ne "commit message: "
      #read msg
      #echo -ne "tag: "
      #read tag
      #echo "committing $vdORIGINAL..."
      #cvs commit -m "$msg" $vdORIGINAL
      #echo "tagging $vdORIGINAL $tag..."
      #cvs tag -F $tag $vdORIGINAL
      vCommitTag
      vprint "mv $vdORIGINAL.$vdLOCALSUFFIX $vdORIGINAL"
      mv $vdORIGINAL.$vdLOCALSUFFIX $vdORIGINAL
      exit
      ;;
    cc)
      #echo -ne "commit message: "
      #read msg
      #echo "committing $vdORIGINAL..."
      #cvs commit -m "$msg" $vdORIGINAL
      #echo "tagging $vdORIGINAL CUR..."
      #cvs tag -F CUR $vdORIGINAL
      vCommitTag CUR
      vprint "cp $vdORIGINAL.$vdLOCALSUFFIX $vdORIGINAL"
      cp $vdORIGINAL.$vdLOCALSUFFIX $vdORIGINAL
      exit
      ;;
    Cc)
      #echo -ne "commit message: "
      #read msg
      #echo "committing $vdORIGINAL..."
      #cvs commit -m "$msg" $vdORIGINAL
      #echo "tagging $vdORIGINAL CUR..."
      #cvs tag -F CUR $vdORIGINAL
      vCommitTag CUR
      vprint "mv $vdORIGINAL.$vdLOCALSUFFIX $vdORIGINAL"
      mv $vdORIGINAL.$vdLOCALSUFFIX $vdORIGINAL
      exit
      ;;
    x)
      vprint "exit"
      break
      ;;
    *)
      echo "unknown cmd"
      ;;
  esac
done
